version: '3.3'

services:

  newsies-api:
    image: newsies-backend
    build:
      context: .
      args:
        PYTHON_VERSION: 3.7
    ports:
      - "5000:5000"
    expose:
      - "5000" 
    volumes:
      - ./:/data
    depends_on:
      - gutenberg-api