version: '3.3'

services:

  gutenberg-api:
    image: gutenberg-api
    build:
      context: ./gutenberg/
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.7
    ports:
      - 80:80
    restart: "${APP_RESTART}"
    environment:
      - GUTENBERG_DATA=/data/${APP_DB}
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./:/data

  newsies-api:
    image: newsies-backend
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - gutenberg-api